version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - ruby
  - dependencies
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  labels:
  - actions
  - dependencies
