services:
  search:
    image: opensearchproject/opensearch:2.11.0
    ports:
      - "9600:9600"
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    volumes:
      - search-data:/usr/share/opensearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:9600/_cluster/health?wait_for_status=green&timeout=50s || exit 1 ",
        ]
      retries: 3
      interval: 5s
      timeout: 3s

  search-console:
    image: opensearchproject/opensearch-dashboards:2.11.0
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://search:9200"]'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -u admin:admin --fail --silent http://localhost:5601/api/status || exit 1",
        ]
      interval: 5s
      timeout: 3s
    depends_on:
      search:
        condition: service_healthy

volumes:
  search-data: {}
