services:

  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d postgres -h localhost -p 5432 || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 3

  search:
    image: opensearchproject/opensearch:2.19.1
    ports:
      - "9600:9600"
      - "9200:9200"
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Howcoq-kinhin-timxi6
      - discovery.type=single-node
    volumes:
      - search-data:/usr/share/opensearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail -k --silent https://admin:Howcoq-kinhin-timxi6@localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1 ",
        ]
      retries: 3
      interval: 5s
      timeout: 3s

  search-console:
    image: opensearchproject/opensearch-dashboards:2.19.1
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://search:9200"]'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail -k --silent http://admin:Howcoq-kinhin-timxi6@localhost:5601/api/status || exit 1",
        ]
      interval: 5s
      timeout: 3s
    depends_on:
      search:
        condition: service_healthy

volumes:
  search-data: {}
  db-data: {}
