services:
  search:
    image: opensearchproject/opensearch:3.6.0
    ports:
      - "9600:9600"
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - search-data:/usr/share/opensearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1",
        ]
      retries: 3
      interval: 5s
      timeout: 3s

  search-console:
    image: opensearchproject/opensearch-dashboards:3.6.0
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://search:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:5601/api/status || exit 1",
        ]
      interval: 5s
      timeout: 3s
    depends_on:
      search:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: rubyapi
      POSTGRES_PASSWORD: rubyapi_password
      POSTGRES_DB: rubyapi_development
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rubyapi -d rubyapi_development"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  search-data: {}
  postgres-data: {}
