FROM ruby:4.0.3-slim

WORKDIR /rails

# Install required packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential libffi-dev libpq-dev libyaml-dev pkg-config curl git && \
    rm -rf /var/lib/apt/lists/*

# Update gems and bundler
RUN gem update --system --no-document && \
    gem install -N bundler

ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_WITHOUT="" \
    RAILS_ENV=development

# Copy Gemfile and install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install
