import "./application.css"
import "./logo.svg"
import "./logo-plain.svg"
import "@fortawesome/fontawesome-free/css/solid"
import "@fortawesome/fontawesome-free/css/fontawesome"
import "@fortawesome/fontawesome-free/css/brands"
