service: rubyapi
image: rubyapi

servers:
  web:
    hosts:
      - rubyapi
    options:
      add-host: host.docker.internal:host-gateway

proxy:
  ssl: true
  host: ingress.internal.rubyapi.org
  forward_headers: true

registry:
  server: 794038216860.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: ubuntu

env:
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DD_AGENT_HOST: host.docker.internal
    DD_TRACE_AGENT_PORT: "8126"
    DD_DOGSTATSD_PORT: "8125"
    DD_ENV: production
    DD_SERVICE: rubyapi.org
    DD_VERSION: <%= `git rev-parse --short HEAD`.strip %>
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - CACHE_DATABASE_URL
    - QUEUE_DATABASE_URL

builder:
  arch: amd64
