name: Dependabot security label

on: pull_request_target

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label:
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: meta
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0

      - name: Add security label
        if: steps.meta.outputs.alert-state != ''
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr edit "$PR_URL" --add-label "security"

      - name: Add security-critical label
        if: steps.meta.outputs.alert-state != '' && steps.meta.outputs.cvss >= 7.0
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr edit "$PR_URL" --add-label "security-critical"
